apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
spec:
  replicas: "{{ .Values.replicas }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
      - name: "{{ .Values.name }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: "{{ .Values.port }}"
        readinessProbe:
          httpGet:
            path: /
            port: "{{ .Values.port }}"
          initialDelaySeconds: 5
          periodSeconds: 5
