#apiVersion: v1
#kind: Namespace
#metadata:
#  name: my-namespace
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
#  namespace: my-namespace
  name: esp-echo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: esp-echo
    spec:
      containers:
      - name: my-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
