node{
    def app

    stage('Checkout') {
        git branch: 'master', credentialsId: 'whiteheal_git', url: 'https://github.com/k0938350210/task.git'
    }
   stage('Build image') {
        dir('demo3/docker') {
            app = docker.build("zndre/softserve")
        }
   }
    stage('Push to registry') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub'){
            app.push('latest')
            app.push("${env.BUILD_ID}")
        }
    }
    stage("Helm deploy") {
    withKubeConfig([credentialsId: '252844ec-fa83-4dbd-af3b-07934e6f2e42',
                    serverUrl: 'https://api-softserve-k8s-local-tl03un-1783831593.eu-central-1.elb.amazonaws.com',
                    contextName: 'softserve.k8s.local'
                    ]) {
            sh 'helm upgrade --install demo3 demo3/helm'
        }

    }
}
