node{
    def app

    stage('Checkout') {
        git branch: 'master', credentialsId: 'whiteheal_git', url: 'https://github.com/WhiteHeal/softserve.git'
    }
   stage('Build image') {
        dir('docker') {
            app = docker.build("zndre/softserve")
        }
   }
    stage('Push to registry') {
        docker.withRegistry('https://registry.hub.docker.com', 'docker-hub'){
            app.push('latest')
            app.push("${env.BUILD_ID}")
        }
    }
    withKubeConfig([credentialsId: '252844ec-fa83-4dbd-af3b-07934e6f2e42',
                serverUrl: 'https://api-softserve-k8s-local-tl03un-1783831593.eu-central-1.elb.amazonaws.com',
                contextName: 'softserve.k8s.local'
                ]) {
        stage("Helm deploy") {
                sh 'helm upgrade --install demo3 helm'
        }
        stage("Test"){
            sh 'sleep 25'
                sh 'kubectl run test -i --tty --rm --restart=Never --image=yauritux/busybox-curl curl esp-echo'
        }
    }
}